### ISSUE TITLE
数据权限怎么控制

### ISSUE THREAD

**Issue by cmkcmk181** [liuht777/Taroco#17]
界面中在哪里设置数据权限？

**Comment by liuht777** [comment]
现有的页面按钮是做了权限控制的, 你可以看下实现

**Comment by liuht777** [comment]
> 界面中在哪里设置数据权限？

在菜单里面添加功能按钮的资源,然后前端就可以做功能按钮的动态展示了.
如果要做数据库级别的数据权限,Taroco后端有相应的demo, 搜索DataScope.
