### ISSUE TITLE
feign服务调用失败就会一只调用，进入了死循环

### ISSUE THREAD

**Issue by liuliuzx** [liuht777/Taroco#27]
不知道怎么联系你，我在测试的时候发现了这个问题，好像ribbon的配置无效，删掉或者改配置都无效，会一直死循环请求下去。。。

[taroco-authentication-server:10.211.55.2:9001] 2018-10-17 15:58:34.661 ERROR 61955 [http-nio-9001-exec-3] cn.taroco.oauth2.server.feign.fallback.UserServiceFallbackImpl 通过用户名查询用户异常:admin
[taroco-authentication-server:10.211.55.2:9001] 2018-10-17 15:58:34.755 ERROR 61955 [http-nio-9001-exec-3] cn.taroco.oauth2.server.feign.fallback.UserServiceFallbackImpl 通过用户名查询用户异常:admin
[taroco-authentication-server:10.211.55.2:9001] 2018-10-17 15:58:34.841 ERROR 61955 [http-nio-9001-exec-3] cn.taroco.oauth2.server.feign.fallback.UserServiceFallbackImpl 通过用户名查询用户异常:admin
[taroco-authentication-server:10.211.55.2:9001] 2018-10-17 15:58:34.920 ERROR 61955 [http-nio-9001-exec-3] cn.taroco.oauth2.server.feign.fallback.UserServiceFallbackImpl 通过用户名查询用户异常:admin
[taroco-authentication-server:10.211.55.2:9001] 2018-10-17 15:58:34.992 ERROR 61955 [http-nio-9001-exec-3] cn.taroco.oauth2.server.feign.fallback.UserServiceFallbackImpl 通过用户名查询用户异常:admin
[taroco-authentication-server:10.211.55.2:9001] 2018-10-17 15:58:35.072 ERROR 61955 [http-nio-9001-exec-3] cn.taroco.oauth2.server.feign.fallback.UserServiceFallbackImpl 通过用户名查询用户异常:admin
[taroco-authentication-server:10.211.55.2:9001] 2018-10-17 15:58:35.141 ERROR 61955 [http-nio-9001-exec-3] cn.taroco.oauth2.server.feign.fallback.UserServiceFallbackImpl 通过用户名查询用户异常:admin
[taroco-authentication-server:10.211.55.2:9001] 2018-10-17 15:58:35.212 ERROR 61955 [http-nio-9001-exec-3] cn.taroco.oauth2.server.feign.fallback.UserServiceFallbackImpl 通过用户名查询用户异常:admin
[taroco-authentication-server:10.211.55.2:9001] 2018-10-17 15:58:35.293 ERROR 61955 [http-nio-9001-exec-3] cn.taroco.oauth2.server.feign.fallback.UserServiceFallbackImpl 通过用户名查询用户异常:admin
[taroco-authentication-server:10.211.55.2:9001] 2018-10-17 15:58:35.381 ERROR 61955 [http-nio-9001-exec-3] cn.taroco.oauth2.server.feign.fallback.UserServiceFallbackImpl 通过用户名查询用户异常:admin
[taroco-authentication-server:10.211.55.2:9001] 2018-10-17 15:58:35.467 ERROR 61955 [http-nio-9001-exec-3] cn.taroco.oauth2.server.feign.fallback.UserServiceFallbackImpl 通过用户名查询用户异常:admin
[taroco-authentication-server:10.211.55.2:9001] 2018-10-17 15:58:35.551 ERROR 61955 [http-nio-9001-exec-3] cn.taroco.oauth2.server.feign.fallback.UserServiceFallbackImpl 通过用户名查询用户异常:admin
[taroco-authentication-server:10.211.55.2:9001] 2018-10-17 15:58:35.642 ERROR 61955 [http-nio-9001-exec-3] cn.taroco.oauth2.server.feign.fallback.UserServiceFallbackImpl 通过用户名查询用户异常:admin
[taroco-authentication-server:10.211.55.2:9001] 2018-10-17 15:58:35.745 ERROR 61955 [http-nio-9001-exec-3] cn.taroco.oauth2.server.feign.fallback.UserServiceFallbackImpl 通过用户名查询用户异常:admin

**Comment by liuht777** [comment]
嗯 这个问题我知道, 目前没空调这个问题, 你可以帮忙看下, 然后提PR

**Comment by liuht777** [comment]
问题已经解决了哈: https://github.com/liuht777/Taroco/commit/2516296d54a74cb76d4d85ac95c88b223ea3deab
