### ISSUE TITLE
rbac启动失败

### ISSUE THREAD

**Issue by lianglinux5** [liuht777/Taroco#67]
<img width="693" alt="WechatIMG6" src="https://user-images.githubusercontent.com/14293060/56282838-a70e9f80-6142-11e9-9fd3-6b9370009c86.png">

**Comment by liuht777** [comment]
无法看出你是什么问题

**Comment by lianglinux5** [comment]
我本地的redis没有密码，在配置文件里把redis密码设置为空，可以启动了
 谢谢


原始邮件
发件人:liuht777notifications@github.com
收件人:liuht777/TarocoTaroco@noreply.github.com
抄送:恬淡虚无liangxs5@163.com; Authorauthor@noreply.github.com
发送时间:2019年5月7日(周二) 15:20
主题:Re: [liuht777/Taroco] rbac启动失败 (#67)


无法看出你是什么问题
