### ISSUE TITLE
用户管理的生产应用

### ISSUE THREAD

**Issue by linzehuan** [liuht777/Taroco#73]
请问o2o应用里的C端用户和B端商户，管理员，都是用Taroco的用户表来保存吗，然后分配不同的角色吗？

**Comment by liuht777** [comment]
这个取决于你自己

**Comment by lhzhou180606** [comment]
Unknown class to load cn.taroco.common.ribbon.XlabelWeightMetadataRule for class interface com.netflix.loadbalancer.IRule named taroco-rbac-service   没有这个类cn.taroco.common.ribbon.XlabelWeightMetadataRule

**Comment by liuht777** [comment]
你这个是代码和配置不匹配, 现在master代码的配置是在Nacos当中, Nacos 配置脚本在docs下面
